### ISSUE TITLE
ParseTests TestArrayParse and TestMultilineValueParse failure

### ISSUE THREAD

**Issue by Calytic** [dezhidki/Tommy#3]
This is a great project!  Please keep it up!

I just want to note that TestArrayParse and TestMultilineValueParse will fail on Windows in some cases if there is a newline mismatch.

In these cases, the "input" variable has newlines encoded in the .CS file as `\n` but the tests check for equality with newlines encoded with `\r\n`.  Aside from the newline mismatch, the tests work perfectly.

```
> dotnet test TommyTests
Microsoft (R) Build Engine version 16.4.0-preview-19529-02+0c507a29b for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
Test run for C:\tommy\TommyTests\bin\Debug\net46\uMod.Tests.dll(.NETFramework,Version=v4.6)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
  X TestArrayParse [61ms]
  Error Message:
   Assert.AreEqual failed. Expected:<Just to make sure
we still work as expected
because reasons>. Actual:<Just to make sure
we still work as expected
because reasons>.
  Stack Trace:
     at TommyTests.Utils.TomlNodesAreEqual(Assert assert, TomlNode expected, TomlNode actual, Boolean ignoreComments) in C:\tommy\TommyTests\Utils.cs:line 20
   at TommyTests.Utils.TomlNodesAreEqual(Assert assert, TomlNode expected, TomlNode actual, Boolean ignoreComments) in C:\tommy\TommyTests\Utils.cs:line 41
   at TommyTests.Utils.TomlNodesAreEqual(Assert assert, TomlNode expected, TomlNode actual, Boolean ignoreComments) in C:\tommy\TommyTests\Utils.cs:line 50
   at TommyTests.ParseTests.TestArrayParse() in C:\tommy\TommyTests\ParseTests.cs:line 338

  X TestMultilineValueParse [1ms]
  Error Message:
   Assert.AreEqual failed. Expected:<The first newline is
trimmed in raw strings.
  All other whitespace
  is preserved.
>. Actual:<The first newline is
trimmed in raw strings.
  All other whitespace
  is preserved.
>.
  Stack Trace:
     at TommyTests.Utils.TomlNodesAreEqual(Assert assert, TomlNode expected, TomlNode actual, Boolean ignoreComments) in C:\tommy\TommyTests\Utils.cs:line 20
   at TommyTests.Utils.TomlNodesAreEqual(Assert assert, TomlNode expected, TomlNode actual, Boolean ignoreComments) in C:\tommy\TommyTests\Utils.cs:line 50
   at TommyTests.ParseTests.TestMultilineValueParse() in C:\tommy\TommyTests\ParseTests.cs:line 561


Test Run Failed.
Total tests: 11
     Passed: 9
     Failed: 2
```

Thank you for considering this.

**Comment by dezhidki** [comment]
Hi,

thanks for pointing this out! The problematic behaviour depends on your git configuration: if you checkout files in CRLF, the tests do pass fine on Windows. However, if you checkout in LF, the tests do indeed fail. 
Naturally, the same issue persists on Linux but in a reversed way.

I'll update the assertion helper to make it agnostic of newline styles for the time being.

Thanks again!
